### ISSUE TITLE
Where should capability flags go?

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-ls-xcp#10]
We need to announce if an FMU supports internal and/or external XCP server.
As of writing, @PTaeuberDS proposes to use two entries in the version.xml file.

We could also add two constant (structural) parameters in the modelDescription.xml (alongside the org.fmi-standard.fmi-ls-xcp.EnableInternalXcpService fixed, structural parameter and its two friends).

Other ideas? Annotations (but where?)? @pmai?

**Comment by chrbertsch** [comment]
Discussion: 
Klaus: would it not just be a constant (not structural)
Andreas: is something like a capability flag.
Patrick: constant structural parameters are not allowed.

Andreas: we could use the modeldescription.xml, or a specific xml file for this layered standard. (see https://github.com/modelica/fmi-standard/issues/1825 for an xsd description describing the version)
@pmai : what do you think?

**Comment by chrbertsch** [comment]
Is already addressed in the current proposal (https://github.com/modelica/fmi-ls-xcp/tree/main/schema), shall be updated in #11
