### ISSUE TITLE
Get information on LS-XCP prototype implementation (commitment, time schedule)

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-ls-xcp#13]
... until March 13

dSPACE: example FMI 3.0 LS-XCP available
Synopys: prototype available for both FMI 3.0 LS-XCP export and import (both internal and external) in Silver
ETAS
PMSF: manually written FMI 2.0 FMU with LS-XCP support available

**Comment by andreas-junghanns** [comment]
Discussed today in Munich - agreement reached.
