### ISSUE TITLE
Clarify valid combinations for containsXcpService and supportsExternalXcpService

### ISSUE THREAD

**Issue by pmai** [modelica/fmi-ls-xcp#15]
The way that the spec is currently phrased would allow both `containsXcpService` and `supportsExternalXcpService` to be `true`, which is intended, but it would also allow both to be `false`, which I am not sure is intentional, nor what the semantic meaning of this would be.

If at least one of the two flags must be true, then the spec should say so, otherwise the spec should spell out what the meaning of both of them being false would be.

**Comment by PTaeuberDS** [comment]
In Section 5 "External XCP Service" this is written as non-normative text:
"Note that the FMU must set at least one of the attributes containsXcpService or supportsExternalXcpService to true to make use of this layered standard."
This implies that it is not forbidden but would make this LS useless.
Is this sufficient or shall we forbid it explicitly in normative text in a more central place in the document?

**Comment by PTaeuberDS** [comment]
FMI Design Meeting Paderborn:

(How) should we rename the 1st attribute to:
1) No renaming
2) ContainsInternalXcpService -> ContainsXcpService
3) ContainsInternalXcpService -> ProvidesXcpService

1: 5
2: 7
3: 6
Abstain: 2

Should we rename the 2nd attribute to:
2) SupportsExternalXcpService -> SupportsDirectMemoryAccessViaA2L

Yes: 14
No: 1
Abstain: 2

**Comment by PTaeuberDS** [comment]
Addressed in #26/#27, respectively.

**Comment by PTaeuberDS** [comment]
We should change the non-normative recommendation for valid combinations of containsXcpService and supportsDirectMemoryAccessViaA2L to normative text and mandate that not both of them must be false.

I will do this in a following PR.
