### ISSUE TITLE
Spec should give more leeway in the default address/port in A2L/interface

### ISSUE THREAD

**Issue by pmai** [modelica/fmi-ls-xcp#16]
Currently the spec states:

    The default IP address assigned by the FMU exporter shall be localhost, i.e. 127.0.0.1, which fits in many cases. 

This should be loosened a bit, since there are use cases where the XCP service of the FMU runs on a specific machine (e.g. in the cases of FMU remoting or other forms of FMU proxying, where the FMU running on the simulator only interfaces to the actual SW/FMU, and hence the XCP slave is also on that machine).

**Comment by PTaeuberDS** [comment]
Addressed in #26/#27, respectively.

@andreas-junghanns Not quite sure what your addition refers to. Maybe you can check/fix this by yourself.
At least for the port it is mentioned that it must be consistent throughout FMU/XCP slave configuration and A2L file.

**Comment by andreas-junghanns** [comment]
> Addressed in #26/#27, respectively.
> 
> @andreas-junghanns Not quite sure what your addition refers to. Maybe you can check/fix this by yourself. At least for the port it is mentioned that it must be consistent throughout FMU/XCP slave configuration and A2L file.

Inside the a2l file(s), the IP/Port combinations are also specified. What we define in the .xml file must not contradict the a2l definitions.
