### ISSUE TITLE
Ensure differentiation between XCP Slave vs. non-slave requirements is clear

### ISSUE THREAD

**Issue by pmai** [modelica/fmi-ls-xcp#2]
The layered standard shall be applicable for two different use cases:

1. FMU is shipped with an a2l file that is employed via an FMU embedded XCP slave
2. FMU is shipped with an a2l file that is used directly for memory access

It is currently not always clear which requirements in the standard apply to both cases, or only apply to one of them (e.g. requirement that addresses in the A2L file are relative to the DLL load address is only applicable/relevant to case 2, whereas structural parameters for IP address and port is only applicable to case 1).

The document should clarify this where applicable.

This is a reminder issue to be addressed in final editing.

**Comment by andreas-junghanns** [comment]
Se PR #5.
