### ISSUE TITLE
The structural parameter names in fmi-ls-xcp almost violates the FMI 3.0 "variableNamingConvention = structured" rules

### ISSUE THREAD

**Issue by adriantirea** [modelica/fmi-ls-xcp#21]
The FMI 3.0 `variableNamingConvention = structured` rules are:

> variableNamingConvention = structured
> Structured names are using "." as a separator between hierarchies. A name consists of "_", letters and digits or may consist of any characters enclosed in single apostrophes.
> 

The fmi-ls-xcp proposed structural parameters contain the `-` character that would require single apostrophes enclosure.
```
org.fmi-standard.fmi-ls-xcp.EnableInternalXcpService
org.fmi-standard.fmi-ls-xcp.ListenIpAddress
org.fmi-standard.fmi-ls-xcp.ListenPortNumber
```
I propose renaming the parameters to not need apostrophes.

**Comment by PTaeuberDS** [comment]
FMI Design Meeting Paderborn:
Option 1: Replace with underscore
Option 2: Force namingConvention=flat for Layered Standards

Poll:
Option 1: all but Timo
Option 2: /
Abstain: Timo

=> org.fmi_standard.fmi_ls_xcp.EnableInternalXcpService

**Comment by PTaeuberDS** [comment]
Do we need to add non-normative text in the Core Standard or in the Implementers Guide?
Core Standard: 1
Implementers Guide: 13
None: 2
Abstain: 1
