### ISSUE TITLE
Clarify the fmi-ls-manifest.xml content.

### ISSUE THREAD

**Issue by adriantirea** [modelica/fmi-ls-xcp#22]
If it weren't for the example showing a fmi-ls-manifest.xml (https://github.com/modelica/fmi-ls-xcp/blob/main/docs/examples/fmi_ls_xcp_manifest_example.xml) I would have used the attributes without the xml namespace http://fmi-standard.org/fmi-ls-manifest.

Also, if I read only the fmi-ls-xcp document I do not understand what xml element has these attributes. 

Both above information is present in FMI 3.0.1 RC1, Section "2.6. Versioning and Layered Standards". 
Probably a hint to look for this information there would help.

**Comment by andreas-junghanns** [comment]
Clear after 10 minutes of explanation: this is xml namespaces mechanisms and the table in the standard points to the namespace.
