### ISSUE TITLE
Prepare RC1

### ISSUE THREAD

**Issue by PTaeuberDS** [modelica/fmi-ls-xcp#32]
It was decided in the FMI Design Meeting to tag the first release candidate (RC1).

**Comment by PTaeuberDS** [comment]
I changed the version to 1.0.0-rc.1 in #35.

@chrbertsch @andreas-junghanns 
What else has to be done for tagging RC1?

**Comment by andreas-junghanns** [comment]
@chrbertsch : Do we need release notes? If yes, where?

**Comment by chrbertsch** [comment]
> @chrbertsch : Do we need release notes? If yes, where?

For the initial release they are not necessary.
in future releases we should have something as the "what is new" in FMI 3.0 (https://fmi-standard.org/docs/3.0.1/#fmi-whats-new) in the document (no separate file). Additinally we shall describe also smaller fixes in the Github release page (see https://github.com/modelica/fmi-standard/releases for FMI 3.0.1)

We should list the contributors in an appendix (see https://fmi-standard.org/docs/3.0.1/#_contributors for FMI 3.0)

**Comment by PTaeuberDS** [comment]
As the decision for tagging RC1 was made in the steering committee, can we merge the last Pull Request with the version update?
Then somebody (@chrbertsch ?) can tag the RC1.

**Comment by chrbertsch** [comment]
> As the decision for tagging RC1 was made in the steering committee, can we merge the last Pull Request with the version update?
> Then somebody (@chrbertsch ?) can tag the RC1.

@pmai  or @t-sommer : Could you please do the tagging? (@PTaeuberDS : You could do it also, I made you a maintainer.)
Can we also include 1.0rc1 as version number in the generated html? Will we do this in a branch?
Can  we create a pre-release at https://github.com/modelica/fmi-ls-xcp/releases/new
(@PTaeuberDS : You could do it also, I made you a maintainer. But then check with @t-sommer, who does this for the fmi-standard release)
