### ISSUE TITLE
Do we need a version in (this) layered standard?

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-ls-xcp#6]
Workshop Berlin:
With auto-detect of support for a layered standard (e.g. by finding a specific file inside the FMU), we do not have a clear way to identify which (potential) version of a layered standard is being supported.

We might have to introduce new versions of a layered standard, even if we do want to continue doing the same things, but for a future FMI 3.x or Y.x version --> therefore we believe that the FMU must declare which layered standard and which version(s) it supports.

See https://github.com/modelica/fmi-standard/issues/1825

**Comment by chrbertsch** [comment]
will be addressed by #11
