### ISSUE TITLE
Use consistent capitalization for acronyms

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-ls-xcp#68]
In the FMI specification we (consistently) use all-uppercase for acronyms in variables, attributes, and functions names, e.g. `fmi3GetFMUState`.

LS XCP currently uses a mix of first-uppercase (e.g. `containsXcpService`) and all-uppercase (e.g. `supportsDirectMemoryAccessViaA2L`).

This should be consistent and follow the convention used in the FMI specification.

Candidates:

- `Ip` vs. `IP`
- `Udp` vs. `UDP`
- `Xcp` vs. `XCP`

**Comment by chrbertsch** [comment]
@Pierre:  I will take this into account when I create the other PR
