### ISSUE TITLE
Please review the currenty proposal

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-ls-xcp#7]
And provide company specific feedback, if the proposal is fine for you

**Comment by PenndorfT** [comment]
Review from ETAS by End of November

**Comment by PenndorfT** [comment]
Hello.
some delay but here are my comments as zipped diff.

Timo
[index.diff.zip](https://github.com/modelica/fmi-ls-xcp/files/10236903/index.diff.zip)

**Comment by andreas-junghanns** [comment]
> Hello. some delay but here are my comments as zipped diff.
> 
> Timo [index.diff.zip](https://github.com/modelica/fmi-ls-xcp/files/10236903/index.diff.zip)

Not sure this is a joke, but could you (@PenndorfT) please leave your comments here in plain text? That would make for easier reading and commenting. Thank you!

**Comment by dietmarw** [comment]
@PenndorfT created #8 out of the diff file. Thanks.

**Comment by PTaeuberDS** [comment]
In our dSPACE review several points came up that still need to be clarified from our point of view. This is mostly about the handling of an external XCP service and the handling of source code FMUs.
I will create a Pull Request in the beginning of January. As the handling of an external XCP service is elaborated a bit I will divide the sections into common concepts, internal XCP and external XCP according to the structure of the base standard and fmi-ls-bus.

**Comment by chrbertsch** [comment]
> In our dSPACE review several points came up that still need to be clarified from our point of view. This is mostly about the handling of an external XCP service and the handling of source code FMUs. I will create a Pull Request in the beginning of January. As the handling of an external XCP service is elaborated a bit I will divide the sections into common concepts, internal XCP and external XCP according to the structure of the base standard and fmi-ls-bus.

FMI webmeeting

Andreas:  an external webmeeting is complicated. Could we discuss this soon?
Patrick: an external XCP is already mentioned. I will create a PR and we can discuss it

**Comment by chrbertsch** [comment]
I think we can close this, as feedback was given and addressed
