### ISSUE TITLE
Clarification on multiple model instances per process and address resolution

### ISSUE THREAD

**Issue by Tc-Fast** [modelica/fmi-ls-xcp#73]
The documentation in section 5.3 says:

> In the binary FMU case, the A2L file must contain real addresses, which are relative to the base address of the FMU binary, allowing the external XCP slave to access the memory of the FMU correctly.

How is this compatible with instantiating a model multiple times per process?

**Comment by msuevern** [comment]
When loading a DLL into a process, then the base address of the DLL is assigned by the operating system. This means that a DLL that is instantiated multiple times has a different base address. The document therefore states the addresses must be relative to the base address.

**Comment by Tc-Fast** [comment]
A "modelName.dll" can only be loaded once per process. So there is only a single base address for "modelName.dll". The FMI standard however allows to instantiate a model multiple time from a single "modelName.dll" instance.

**Comment by msuevern** [comment]
I would say either the importer must create a separate process for each instance, or the FMU must manage a "base address" itself in cases where canBeInstantiatedOnlyOncePerProcess = false, but in any case, the A2L file should contain relative addresses. How to implement a FMU with XCP that can be instantiated multiple times per process is not part of the document.

**Comment by Tc-Fast** [comment]
> How to implement a FMU with XCP that can be instantiated multiple times per process is not part of the document.

Since it is not explicitly forbidden to do so, I would argue it is allowed.

**Comment by msuevern** [comment]
In my opinion the document makes no restriction regard this, it only defines how the A2L addresses should looks like.

**Comment by HansOlsson** [comment]
Isn't the obvious solution to restrict this case to binary FMUs that are loaded once if you don't plan to support it? And list that as a restriction

**Comment by msuevern** [comment]
The proposal from dSPACE is to add the follow sentence at the end of the document in the "Known Limitations of the Standard" chapter. 

_If the attribute supportsDirectMemoryAccessViaA2L is set to true, then the attribute canBeInstantiatedOnlyOncePerProcess of the FMU’s model description must also set to true, hence the variables in the A2L file have their unique addresses._

**Comment by chrbertsch** [comment]
FMI Design Webmeeting: 
Looks good. Can you create a PR?
