### ISSUE TITLE
EnableXcpOn{Tcp|Udp}Ip should be EnableXcpOver{Tcp|Udp}Ip

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-ls-xcp#78]

**Comment by PTaeuberDS** [comment]
Can you motivate this change? XCP on Ethernet/TCP/CAN seems to be the common phrase. It is used like this in the ASAM XCP standard, AUTOSAR standard, Wikipedia etc.

**Comment by chrbertsch** [comment]
FMI Design webmeeting
In the new approach the "on"/"over" ist no longer part of the names, only in the explanation text

**Comment by chrbertsch** [comment]
Fixed in the larger rework by @pmai
