### ISSUE TITLE
Create a release candidate

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-ls-xcp#86]
after merging https://github.com/modelica/fmi-ls-xcp/pull/81

**Comment by chrbertsch** [comment]
@pmai ,  @PTaeuberDS  and others: can we create an RC now?

**Comment by chrbertsch** [comment]
@PTaeuberDS : After merging the last open PR, could you please create a new release candidate? Thanks!

**Comment by PTaeuberDS** [comment]
RC 5 is now available.
